server:
  port: 5160
  servlet:
    context-path: /gorgeous
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lan-code-api?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: AAaa123456

gitInfo:
  username:
  password: